package protocol

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/blinklabs-io/gouroboros/cbor"
	"github.com/blinklabs-io/gouroboros/ledger/common"
)

const (
	// TypePlutusScriptV3 is the Cardano text-envelope type for Plutus V3 scripts.
	TypePlutusScriptV3 = "PlutusScriptV3"
)

// PlutusEnvelope is a Cardano CLI / Aiken text envelope for a Plutus script.
type PlutusEnvelope struct {
	Type        string `json:"type"`
	Description string `json:"description"`
	CBORHex     string `json:"cborHex"`
}

// LoadPlutusEnvelope reads a Plutus V3 text envelope from path.
func LoadPlutusEnvelope(path string) (*PlutusEnvelope, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var env PlutusEnvelope
	if err := json.Unmarshal(raw, &env); err != nil {
		return nil, fmt.Errorf("parse plutus envelope: %w", err)
	}
	if env.CBORHex == "" {
		return nil, fmt.Errorf("plutus envelope missing cborHex")
	}
	if env.Type != "" && !strings.EqualFold(env.Type, TypePlutusScriptV3) {
		return nil, fmt.Errorf("unexpected plutus envelope type %q (want %s)", env.Type, TypePlutusScriptV3)
	}
	return &env, nil
}

// SavePlutusEnvelope writes a Plutus V3 text envelope atomically.
func SavePlutusEnvelope(path string, env PlutusEnvelope) error {
	if env.Type == "" {
		env.Type = TypePlutusScriptV3
	}
	if env.Description == "" {
		env.Description = "Generated by Aiken"
	}
	raw, err := json.MarshalIndent(env, "", "  ")
	if err != nil {
		return err
	}
	raw = append(raw, '\n')
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// ScriptFromEnvelope extracts a PlutusV3Script from a text envelope.
// Cardano CLI envelopes store CBOR-in-CBOR; one unwrap yields the ledger script bytes
// (same shape as blueprint compiledCode).
func ScriptFromEnvelope(env *PlutusEnvelope) (common.PlutusV3Script, error) {
	if env == nil {
		return nil, fmt.Errorf("nil plutus envelope")
	}
	outer, err := hex.DecodeString(strings.TrimSpace(env.CBORHex))
	if err != nil {
		return nil, fmt.Errorf("invalid cborHex: %w", err)
	}
	var inner []byte
	if _, err := cbor.Decode(outer, &inner); err != nil {
		// Some producers already emit single-wrapped script bytes.
		return common.PlutusV3Script(outer), nil
	}
	return common.PlutusV3Script(inner), nil
}

// ScriptFromCompiledCodeHex builds a PlutusV3Script from a blueprint compiledCode hex string.
func ScriptFromCompiledCodeHex(compiledCodeHex string) (common.PlutusV3Script, error) {
	b, err := hex.DecodeString(strings.TrimSpace(compiledCodeHex))
	if err != nil {
		return nil, fmt.Errorf("invalid compiledCode hex: %w", err)
	}
	if len(b) == 0 {
		return nil, fmt.Errorf("empty compiledCode")
	}
	return common.PlutusV3Script(b), nil
}

// ScriptHashHex returns blake2b-224(0x03 || script) as lowercase hex (policy id).
func ScriptHashHex(script common.PlutusV3Script) string {
	h := script.Hash()
	return hex.EncodeToString(h[:])
}

// WrapCompiledCodeEnvelope builds a Cardano CLI PlutusScriptV3 envelope from compiledCode bytes.
func WrapCompiledCodeEnvelope(compiledCode []byte, description string) (PlutusEnvelope, error) {
	if len(compiledCode) == 0 {
		return PlutusEnvelope{}, fmt.Errorf("empty compiled code")
	}
	outer, err := cbor.Encode(compiledCode)
	if err != nil {
		return PlutusEnvelope{}, fmt.Errorf("cbor-wrap compiled code: %w", err)
	}
	if description == "" {
		description = "Generated by Aiken"
	}
	return PlutusEnvelope{
		Type:        TypePlutusScriptV3,
		Description: description,
		CBORHex:     hex.EncodeToString(outer),
	}, nil
}

// LoadPlutusV3Script loads a .plutus envelope and returns the ledger script bytes.
func LoadPlutusV3Script(path string) (common.PlutusV3Script, error) {
	env, err := LoadPlutusEnvelope(path)
	if err != nil {
		return nil, err
	}
	return ScriptFromEnvelope(env)
}
